on: push
name: Run Laravel tests
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: "testing"
      mongo:
        image: mongo:latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install php extensions
        run: |
          apt-get update
          apt-get install -y php-pear php8.1-dev php8.1-xml
          pecl install mongodb
          echo "extension=mongodb.so" | tee -a /etc/php/8.1/cli/conf.d/20-mongodb.ini

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Install front-end dependencies
        run: |
          npm install
          npm run build

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
