name: Laravel Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: testing
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - name: Install php extensions
        run: |
          apt-get update
          apt-get install -y php-pear php8.1-dev php8.1-xml
          pecl install mongodb
          echo "extension=mongodb.so" | tee -a /etc/php/8.1/cli/conf.d/20-mongodb.ini
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install front-end dependencies
        run: |
          npm install
          npm run build

      - name: Run test suite
        run: vendor/bin/phpunit --verbose
        env:
          APP_ENV: testing
